language: php

php:
    - 7.1
    - 7.0
    - 5.6

cache:
    directories:
        - ~/.composer/cache/files
    #yarn: true

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer update --prefer-dist
    #- (cd tests/Application && yarn install)

script:
    - composer validate --strict

