winzou_state_machine:
    sylius_shipment:
        states:
            splitted: ~
            awaiting: ~
        transitions:
            split:
                from: [cart]
                to: splitted
#            manual_split:
#                from: [cart, splitted, request_shipping]
#                to: request_shipping
    sylius_order_shipping:
        transitions:
            manual_split:
                from: [ready, cart, splitted, request_shipping]
                to: request_shipping
        callbacks:
            after:
                app_split_shipment:
                    on: [request_shipping]
                    do: ["@urbanara.order_splitter.manager", "executeRules"]
                    args: ["object"]
