winzou_state_machine:
    sylius_shipment:
        states:
            splitted: ~
            awaiting: ~
        transitions:
            split:
                from: [cart]
                to: splitted
    sylius_order_shipping:
        callbacks:
            after:
                app_split_shipment:
                    on: [request_shipping]
                    do: ["@urbanara.order_splitter.manager", "executeRules"]
                    args: ["object"]

services:
    urbanara.order_splitter.rule.twenty_eighty:
        class: Urbanara\OrderSplitterPlugin\Splitter\Rules\TwentyEightyRule
        tags:
            - { name: 'urbanara.order_splitter_plugin.rule' }

    urbanara.order_splitter.rule.fifty_fifty:
        class: Urbanara\OrderSplitterPlugin\Splitter\Rules\FiftyFiftyRule
        tags:
            - { name: 'urbanara.order_splitter_plugin.rule' }

    urbanara.order_splitter.manager:
        class: Urbanara\OrderSplitterPlugin\Splitter\SplitManager
        arguments: ['@sylius.factory.shipment', '@logger']
